
// for (let index = 0; index < 200; index++) {
    let firstH1 = document.createElement("H1")
    firstH1.innerText = "I am H2 and I got generated by JavaScript"
    document.body.appendChild(firstH1)

        // let pWithId = document.getElementById("message")
        // let pWithId = document.getElementsByClassName("the-red-text")
        // pWithId.innerText = "I am not a message"
        // pWithId.style.color = "green"
        // document.body.style.backgroundColor = "Yellow"


    // let pWithId = document.getElementsByClass("message")
    // let elementsWithClasses = document.getElementsByClassName("the-red-text")
    // elementsWithClasses[0].innerText = "I am not a message"
    // elementsWithClasses[0].style.color = "green"
    // elementsWithClasses[1].innerText = "I am mo w"
    // elementsWithClasses[1].style.color = "blue"
    // document.body.style.backgroundColor = "Yellow"

    let elementsWithClasses = document.getElementsByName("nice-names")
    elementsWithClasses[0].innerText = "I am not a nice message"
    elementsWithClasses[0].style.color = "green"
    elementsWithClasses[1].innerText = "I am mo w"
    elementsWithClasses[1].style.color = "blue"
    document.body.style.backgroundColor = "Yellow"

    // let allPs = document.getElementsByTagName("p")
    // allPs[0].style.color = "purple"
    // allPs[1].style.color = "purple"
    // allPs[2].style.color = "purple"

    let allPs = document.querySelector(".the-red-text")
    allPs[0].style.color = "red"
    allPs[1].style.color = "red"
    allPs[2].style.color = "red"


// for (let index = 0; index < 200; index++) {
    // let firstDiv = document.createElement("div")
    // firstDiv.innerText = "This DIV is the first Div in this document"
    // document.body.appendChild(firstDiv)

// }



// let niceSpan = document.createElement("span")
// niceSpan.innerHTML = "<p> hello world, I am the first line</p>"
// document.body.insertBefore(niceSpan,firstDiv)

//document.body.removeChild(niceSpan)

// let theP =  document.getElementById("message1")
// theP.innerHTML = "hello world"

// let allTheReds = document.getElementsByClassName("the-red-text")
// console.log(allTheReds[0].innerHTML)
// allTheReds[1].innerHTML = "Yes or no"
// console.log(allTheReds[1].innerHTML)

// let iLikes = document.getElementsByName("ilike")
// console.log(iLikes[0].innerHTML)
// console.log(iLikes[1].innerHTML)

// let count = 0;
// while (count < 200) {
//     console.log("count is " +  count)
//     iLikes[0].textContent = "I like Ethiopia"
//     iLikes[1].textContent = "I like Kenya"
//     count++
// }

